-- phpMyAdmin SQL Dump
-- version 4.9.3
-- https://www.phpmyadmin.net/
--
-- Host: localhost:8889
-- Generation Time: Aug 10, 2020 at 09:22 PM
-- Server version: 5.7.26
-- PHP Version: 7.3.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `venba`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `material_no` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `concept_id` bigint(20) UNSIGNED NOT NULL,
  `cat_id` bigint(20) UNSIGNED NOT NULL,
  `sub_cat_id` bigint(20) DEFAULT NULL,
  `brand_id` bigint(20) UNSIGNED DEFAULT NULL,
  `type_id` bigint(20) UNSIGNED DEFAULT NULL,
  `compatibility_id` bigint(20) UNSIGNED DEFAULT NULL,
  `power_consumption_id` bigint(20) UNSIGNED DEFAULT NULL,
  `physical_spec` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `light_color` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `introduction` longtext COLLATE utf8mb4_unicode_ci,
  `accessories_required` longtext COLLATE utf8mb4_unicode_ci,
  `warranty` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `technical_spec` longtext COLLATE utf8mb4_unicode_ci,
  `additional_features` longtext COLLATE utf8mb4_unicode_ci,
  `wired_wireless` enum('wired','wireless') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `price` bigint(20) UNSIGNED DEFAULT NULL,
  `igst` bigint(20) UNSIGNED DEFAULT NULL,
  `sgst` bigint(20) UNSIGNED DEFAULT NULL,
  `transit` bigint(20) UNSIGNED DEFAULT NULL,
  `additional_properties` longtext COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `name`, `material_no`, `concept_id`, `cat_id`, `sub_cat_id`, `brand_id`, `type_id`, `compatibility_id`, `power_consumption_id`, `physical_spec`, `light_color`, `introduction`, `accessories_required`, `warranty`, `technical_spec`, `additional_features`, `wired_wireless`, `price`, `igst`, `sgst`, `transit`, `additional_properties`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1, 'Philips - 31184 MEMURU wall lamp LED white 1x14W - 1.2 mtr', '915005573601', 1, 1, 7, 1, NULL, NULL, NULL, 'Height - 2.5 cm Length-118.2 cm Net weight-0.248 kg Width-2.5 cm', 'white', 'Refine your sanctuary with superb white ambiance to heighten your mood. Showcase your intricate wall features and engulf your space with an even glow in every corner with Philips Hue White Ambiance Memuru LED cove light.', 'Philips hue bridge required', '1 year', 'Technical specifications Lifetime up to-20,000 hour(s) Total lumen output fixture-1000 lm Mains power-Range 220 V - 240 V 50-60 Hz Fixture dimmable-No LED-Yes Built in LED-Yes Energy class included light source Built in LED Number of bulbs-1 Wattage bulb included-14 W IP code-IP20 protection against objects bigger than 12.5 mmno protection against water Class of protection- II - double insulated', '', NULL, 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2, 'Philips - 31185 MEMURU wall lamp LED white 1x11W - 0.8 mtr', '915005573602', 1, 1, 7, 1, NULL, NULL, NULL, 'Height-2.5 cm Length-88.2 cm Net weight-0.195 kg Width-2.5 cm', 'white', 'Refine your sanctuary with superb white ambiance to heighten your mood. Showcase your intricate wall features and engulf your space with an even glow in every corner with Philips Hue White Ambiance Memuru LED cove light.', 'Philips hue bridge required', '1 year', 'Lifetime up to-20,000 hour(s) Total lumen output fixture-750 lm Mains power-Range 220 V - 240 V 50-60 Hz Fixture dimmable-No LED-Yes Built in LED-Yes Energy class included light source-Built in LED Number of bulbs-1 Wattage bulb included-11 W IP code-IP20 protection against objects bigger than 12.5 mm-no protection against water Class of protection- II - double insulated', '', NULL, 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3, 'Philips - 31186 MEMURU wall lamp LED white 1x8W - 0.6 mt', '915005573603', 1, 1, 7, 1, NULL, NULL, NULL, '• Height: 2.5 cm • Length: 58.2 cm • Net weight: 0.143 kg • Width: 2.5 cm', 'white', 'Refine your sanctuary with superb white ambiance to heighten your mood. Showcase your intricate wall features and engulf your space with an even glow in every corner with Philips Hue White Ambiance Memuru LED cove light.', 'Philips hue bridge required', '1 year', '• Lifetime up to: 20,000 hour(s) • Total lumen output fixture: 500 lm • Mains power: Range 220 V - 240 V, 50-60 Hz • Fixture dimmable: No • LED: Yes • Built in LED: Yes • Energy class included light source: Built in LED • Number of bulbs: 1 • Wattage bulb included: 8 W • IP code: IP20, protection against objects bigger than 12.5 mm, no protection against water • Class of protection: II - double insulated', '', NULL, 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4, 'Philips - 31187 MEMURU wall lamp LED white 1x5W - 0.3 mtr', '915005573604', 1, 1, 7, 1, NULL, NULL, NULL, 'Height-2.5 cm Length-32.2 cm Net weight-0.098 kg Width-2.5 cm', 'white', 'Refine your sanctuary with superb white ambiance to heighten your mood. Showcase your intricate wall features and engulf your space with an even glow in every corner with Philips Hue White Ambiance Memuru LED cove light.', 'Philips hue bridge required', '1 year', 'Lifetime up to-20,000 hour(s) Total lumen output fixture-250 lm Mains power-Range 220 V - 240 V-50-60 Hz Fixture dimmable-No LED-Yes Built in LED-Yes Energy class included light source-Built in LED Number of bulbs-1 Wattage bulb included-5 W IP code-IP20 protection against objects bigger than 12.5 mm-no protection against water Class of protection-II - double insulated', '', NULL, 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5, 'Philips - Wellness Hue table lamp black 1x9.5W 230', '915005401201', 1, 1, 8, 1, NULL, NULL, NULL, 'Height 19.3 cm Weight 1.46 kg Width 18.6cmm Depth-18.6cm', 'white', 'Light for your moments from sunrise to sunset Include the Wellness Philips Hue white ambiance table lamp in your Philips Hue system and enjoy natural white light that helps you to wake up, energise, concentrate, read and relax. Enjoy the timeless design of this nice table lamp.', 'Philips hue bridge required', '1 year', 'Mains power -Range 220 V–240 V, 50-60 Hz, Bulb technology -230 V, Number of bulbs -1 Fitting/cap -E27 Wattage bulb included -9.5 W Maximum wattage replacement bulb -15 W Light colour -cool white Fixture dimmable -Yes LED -Yes Built-in LED -YES Energy class included light source -built-in LED + bulb of class A+, Fixture is compatible with bulb(s) of class -A++ to E Lifetime up to -25,000, hrs IP code -IP20 protection against objects bigger than 12.5 mm no protection against water Class of protection - II - double insulated, Light source equivalent to traditional bulb of - 60 W Lumen output bulb included -806', '', NULL, 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6, 'Philips-COL Hue Lightstrip Plus 1m extent India', '915005240701', 1, 1, 9, 1, NULL, NULL, NULL, 'Height-0.5 cm Length-100 cm Width-1.5 cm', 'multi colour', 'The most flexible light source imagineable. Extend your Philips Hue Lightstrip Plus with these 1 meter extensions for larger surfaces. Shape it, attach it to any solider surface and enjoy high lumen output', 'Philips hue bridge required', '1 year', 'Mains power-Range 220 V - 240 V Fixture dimmable-Yes Number of bulbs-1 Wattage bulb included - IP code-IP20 protection against objects bigger than 12.5 mm-no protection against water Class of protection-II - double insulated', 'Color changing (LED)-Yes Diffused light effect-Yes Dimmable-Yes LED integrated-Yes Power adapter included-Yes Universal Plug-Yes ZigBee Light Link-Yes', NULL, 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7, 'Philips-COL Hue Lightstrip Plus 2m India', '915005240601', 1, 1, 9, 1, NULL, NULL, NULL, 'Height-0.5 cm Length-200 cm Net weight-0.337 kg Width-1.5 cm', 'multi colour', 'Add a LightStrip Plus to your Philips Hue system and create an immersive experience under bars or cabinets and behind entertainment systems. Lightstrip Plus gives the flexibility to bend, cut and extend for the application of your choice', 'Philips hue bridge required', '1 year', 'Mains power-50-60 Hz Range 220 V - 240 V Fixture dimmable-Yes LED-Yes Number of bulbs-1 Wattage bulb included - IP code-IP20 protection against objects bigger than 12.5 mm-no protection against water Class of protection-II - double insulated', 'Color changing (LED)-Yes Diffused light effect-Yes Dimmable-Yes LED integrated-Yes Power adapter included-Yes Universal Plug-Yes ZigBee Light Link-Yes', NULL, 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(8, 'Philips Hue 10W A60 B22 IN', '929001257412', 1, 1, 10, 1, NULL, NULL, NULL, 'Height-16.500 cm Length-7.500 cm Width-8.800 cm', 'White and colored light', 'Include a Philips Hue white and color ambiance bulb in your Philips Hue system and experience high quality white and colored light that offers you endless possibilities.', 'Philips hue bridge required', '1 year', 'Color temperature-2000K-6500K +16 million colors Diameter-62 mm Energy efficiency label-A+ Fitting-B22 Form factor-A60 Height-110 mm Input voltage-220V-240V Lifetim-25,000 hour(s) Light output Dimmable via smart device only- >80 CRI @ 4000K Lumen output-806 lm @ 4000K Max. standby power-0,2 W Number of switching cycles-50,000 Power factor->0.5 Rated lifetime-25,000 hour(s) Software upgradable-Yes Start up-Instant 100% light output Wattage-10 W Wattage equivalent-60 W', '', NULL, 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(9, 'Philips Hue 10W A60 E27 3 set IN', '929001257314', 1, 1, 10, 1, NULL, NULL, NULL, 'Height-21.000 cm Length-10.200 cm Width-21.000 cm', 'White and colored light', 'With Philips Hue white and color ambiance you can transform your lighting into an extraordinary experience. Connected home lighting offers colored lighting that can be synced to your music, TV and games for immersive effects', 'Philips bridge included', '1 year', 'Color temperature-2000K-6500K +16 million colors Diameter-62 mm Energy efficiency label-A+ Fitting-E27 Form factor-A60 Height-110 mm Input voltage-220V-240V Lifetime-25,000 hour(s) Light output Dimmable via smart device only->80 CRI @ 4000K Lumen output-806 lm @ 4000K Max. standby power-0,2 W Number of switching cycles-50,000 Power factor->0.5 Rated lifetime-25,000 hour(s) Software upgradable-Yes Start up-Instant 100% light output Wattage-10 W Wattage equivalent-60 W', '', NULL, 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(10, 'Philips Hue 10W A60 E27 IN', '929001257315', 1, 1, 10, 1, NULL, NULL, NULL, 'Height-16.500 cm Length-7.500 cm Width-8.800 cm', 'White and colored light', 'Include a Philips Hue white and color ambiance bulb in your Philips Hue system and experience high quality white and colored light that offers you endless possibilities. 1 x E27 bulb White and colored light', 'Philips bridge included', '1 year', 'Color temperature-2000K-6500K +16 million colors Diameter-62 mm Energy efficiency label-A+ Fitting-E27 Form factor-A60 Height-110 mm Input voltage-220V-240V Lifetime-25,000 hour(s) Light output- Dimmable via smart device only->80 CRI @ 4000K Lumen output-806 lm @ 4000K Max. standby power-0,2 W Number of switching cycles-50,000 Power factor->0.5 Rated lifetime-25,000 hour(s) Software upgradable-Yes Start up-Instant 100% light output Wattage-10 W Wattage equivalent-60 W', '', NULL, 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11, 'Philips Hue DIM Switch IN', '929001173764', 1, 6, 25, 1, NULL, NULL, NULL, 'Height-16.500 cm Length-5.500 cm Width-8.800 cm', '', 'Enrich your system with the Philips Hue dimmer switch and enjoy smooth wireless dimming. The switch works as a normal wall switch and dimmer. Place it anywhere you want, using screws or the adhesive tape on the back plate of the switch. Wireless installation Automates your lights', '', '1 year', 'Batteries included-1 x CR2450 Frequency band-2400 - 2483.5 MHz Lifetime-50000 clicks Max. lights per switch-10 if not linked to Hue bridge Minimal battery lifetime-3 year(s) Software upgradeable-when connected to Hue bridge Switch depth-11 mm Switch height-92 mm Switch width-35 mm Wall plate depth-14 mm Wall plate height-115 mm Wall plate width-70 mm Weight including wall plate-67 g Weight of switch-37 g Zigbee Light link-protocol IEEE 802.15.4 Minimal range indoor-500 inch', 'Inside the box : Hue dimmer switch - 1', NULL, 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12, 'Philips-45037 MUSCARI SMALL CEILING', '915005236601', 1, 6, 25, 1, NULL, NULL, NULL, 'Height-10.9 cm Length-53.5 cm Net weight-3.400 kg Width-53.5 cm', 'white', 'Experience light for your moments and ambiance from warm white to cool daylight with Philips Hue White ambiance Muscari LED ceiling light. Helps you to fall asleep and wake up gently, energize and help you to concentrate, read and relax. Dimmer switch included LED integrated Aluminium Smart control with Hue bridge*', 'Philips hue bridge required', '1 year', 'Lifetime up to-30,000 hour(s) Light source equivalent to traditional bulb of-216 W Total lumen output fixture-2200 lm Bulb technology LED-24 V Light color-cool white Mains power Range 100 V - 240 V-50-60 Hz Fixture dimmable-Yes LED-Yes Built in LED-Yes Number of bulbs-1 Wattage bulb included-40 W Maximum wattage replacement bulb-45 W IP code-IP20 protection against objects bigger than 12.5 mm-no protection against water Class of protection-II - double insulated', 'Material-metal', NULL, 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(13, 'Philips-45038 MUSCARI PENDANT', '915005246601', 1, 1, 11, 1, NULL, NULL, NULL, 'Height maximum-150 cm Height minimum-60 cm Length-53.5 cm Net weight-3.900 kg Width-53.5 cm', 'white', 'Experience light for your moments and ambiance from warm white to cool daylight with Philips Hue White ambiance Muscari LED suspension light. Helps you to fall asleep and wake up gently, energize and help you to concentrate, read and relax. Dimmer switch included LED integrated Aluminium Smart control with Hue bridge*', 'Philips hue bridge required', '1 year', 'Lifetime up to-30,000 hour(s) Light source equivalent to traditional bulb of-216 W Total lumen output fixture-2200 lm Bulb technology-LED-24 V Light color-cool white Mains power-Range 110 V - 240 V-50-60 Hz Fixture dimmable-Yes LED-Yes Built in LED-Yes Energy class included light source-Built in LED Number of bulbs-1 Wattage bulb included-40 W IP code-IP20 protection against objects bigger than 12.5 mm-no protection against water Class of protection-II - double insulated', 'Material-metal Type-Suspension light', NULL, 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(14, 'Philips-45039 MUSCARI TABLE LIGHT', '915005291301', 1, 1, 8, 1, NULL, NULL, NULL, 'Height-40.5 cm Length-31 cm Net weight-3.100 kg Width-31 cm', 'white', 'Experience light for your moments and ambiance from warm white to cool daylight with Philips Hue White ambiance Muscari LED ceiling light. Helps you to fall asleep and wake up gently, energize and help you to concentrate, read and relax. LED integrated Aluminium Smart control with Hue bridge* Control with your voice*', 'Philips hue bridge required', '1 year', 'Lifetime up to-20,000 hour(s) Total lumen output fixture-600 lm Mains power-Range 100 V - 240 V-50-60 Hz Fixture dimmable-Yes LED-Yes Built in LED-Yes Energy class included light source-Built in LED Number of bulbs-1 Wattage bulb included-12 W Maximum wattage replacement bulb-15 W IP code-IP20 protection against objects bigger than 12.5 mm-no protection against water Class of protection-III - safe extra low voltage', 'material - Metal Type-Table lamp', NULL, 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15, 'Philips-45040 MUSCARI FLOOR LIGHT', '915005291401', 1, 1, NULL, 1, NULL, NULL, NULL, 'Height-160 cm Length-31 cm Net weight-2.200 kg Width-31 cm', 'white', 'Automate your lights with the Philips Hue White Muscari LED floor light. Dimmable and with soft uniform light distribution, it lets you experience seamless smart control and schedule your light for home automation, wherever you are. LED integrated Aluminium Smart control with Hue bridge* Control with your voice*', 'Philips hue bridge required', '1 year', 'Lifetime up to-20,000 hour(s) Total lumen output fixture-600 lm Mains power Range 100 V - 240 V-50-60 Hz Fixture dimmable-Yes LED-Yes Built in LED-Yes Energy class included light source-Built in LED Number of bulbs-1 Wattage bulb included-12 W Maximum wattage replacement bulb-15 W IP code-IP20 protection against objects bigger than 12.5 mm-no protection against water Class of protection-III - safe extra low voltage', 'Material-metal Type-Floor lamp', NULL, 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16, 'Philips-WITHIN CEILING LAMP LED SILVER 1X55W 24', '915005572601', 1, 1, NULL, 1, NULL, NULL, NULL, 'Height-8.0 cm Length-41.5 cm Net weight-4.500 kg Width-41.5 cm', 'white', 'Minimalist, chic and well-cut Philips Hue White ambiance Within LED ceiling light adds a modernistic touch to your room, in an illuminated square of elegance. Immerse your spaces with light that accentuates the spaciousness of your home. Dimmer switch included LED integrated Aluminium Smart control with Hue bridge*', 'Philips hue bridge required', '1 year', 'Lifetime up to-23,000 hour(s) Total lumen output fixture-2600 lm Mains power-Range 220 V - 240 V-50-60 Hz Fixture dimmable-Yes LED-Yes Built in LED-Yes Number of bulbs-1 Wattage bulb included-55 W Maximum wattage replacement bulb-55 W IP code-IP20 protection against objects bigger than 12.5 mm-no protection against water Class of protection-II - double insulated', 'Color-silver Material-metal Type-Ceiling light', NULL, 1500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(17, 'Philips-WITHIN PENDANT LED SILVER 1X55W 24V', '915005572701', 1, 1, NULL, 1, NULL, NULL, NULL, 'Height maximum-125 cm Height minimum-30 cm Length-80 cm Net weight-3.400 kg Width-15 cm', 'white', 'Like an elegant pendant that dresses up your home, contour your spaces with Philips Hue White ambiance Within LED pendant light. Designed to add flair to your moments, accentuate your activities with soft, evenly distributed brightness. Dimmer switch included LED integrated Aluminium Smart control with Hue bridge*', 'Philips hue bridge required', '1 year', 'Lifetime up to-23,000 hour(s) Total lumen output fixture-1600 lm Mains power-Range 220 V - 240 V-50-60 Hz Fixture dimmable-Yes LED-Yes Built in LED-Yes Energy class included light source-Built in LED Number of bulbs-1 Wattage bulb included-55 W Maximum wattage replacement bulb-55 W IP code-IP20 protection against objects bigger than 12.5 mm-no protection against water Class of protection-II - double insulated', 'Color-silver Material-metal Type-Suspension light', NULL, 1500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(18, 'Philips- Within Table Lamp LED Silver 1X18W 24V', '915005572801', 1, 1, NULL, 1, NULL, NULL, NULL, 'Height-35.3 cm Length-17.5 cm Net weight-1.110 kg Width-38 cm', 'white', 'Philips Hue White ambiance Within LED table light creates the glow you desire with adjustable brightness and ambiance. In a sleek wand of clear brightness, combine style with smart lighting for terrific moments in your home Dimmer switch included LED integrated Aluminium Smart control with Hue bridge', 'Philips hue bridge required', '1 year', 'Lifetime up to-23,000 hour(s) Total lumen output fixture-650 lm Mains power-Range 100 V - 240 V-50-60 Hz Fixture dimmable-Yes LED-Yes Built in LED-Yes Energy class included light source-Built in LED Number of bulbs-1 Wattage bulb included-18 W Maximum wattage replacement bulb-18 W IP code-IP20 protection against objects bigger than 12.5 mm-no protection against water Class of protection-II - double insulated', 'Color-silver Material-metal Type-Table lamp', NULL, 1500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(19, 'Philips- 51108 HUE WA DL 6\" downlights LED white', '915005754501', 1, 1, NULL, 1, NULL, NULL, NULL, 'Cut out length-15 cm Cut out width-15 cm Length-17.5 cm Net weight-0.253 kg Recessed distance-6.5 cm Width-16 cm', 'white', 'This retrofit recessed downlight offers thousands of shades of white light at your fingertips. Control via Bluetooth to instantly turn on and off and the dim in one room, or pair with a Hue Bridge to unlock the full suite of features. LED integrated High quality material Smart control with Hue bridge Control with your voice', 'Philips hue bridge required', '1 year', 'Lifetime up to-25,000 hour(s) Total lumen output fixture-900 lm Mains power-230 V Fixture dimmable-Yes LED-Yes Built in LED-Yes Energy class included light source-Built in LED Number of bulbs-1 Wattage bulb included-10.5 W Maximum wattage replacement bulb-10.5 W IP code-IP20 protection against objects bigger than 12.5 mm-no protection against water Class of protection-II - double insulated', '', NULL, 1500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(20, 'PHILIPS HUE WA 9.5W A60 E27 IN', '929001200126', 1, 1, NULL, 1, NULL, NULL, NULL, 'Gross weight-0.170 kg Height-16.500 cm Length-7.500 cm Width-8.800 cm', 'white', 'Add a Philips Hue white ambiance bulb to your system and enhance your home with shades of white lights. With a range from warm white to cool daylight, this bulb helps you to wake up, relax, read, concentrate or energize 1 x E27 bulb Shades of white (2200-6500K)', 'Philips hue bridge required', '1 year', 'Color temperature-2200K-6500K Diameter-62 mm Energy efficiency label-A+ Fitting-E27 Form factor-A60 Height-110 mm Input voltage-220V-240V Lifetime-25,000 hour(s) Light output-Dimmable via smart device only Warm white to cool daylight- >80 CRI @ 4000K Lumen output-806 lm Max. operation power-9.5 W Max. standby power-0.1 W Number of switching cycles-50,000 Power factor- >0.5 Rated lifetime-25,000 hour(s) Software upgradable when connected to Hue bridge Start up-Instant 100% light output Wattage-9.5 W Wattage equivalent-60 W', 'tested on: Android-Yes Google Nexus-Yes HTC-Yes Motorola Nexus-Yes Note-Yes Samsung Galaxy-Yes', NULL, 1500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(21, 'Philips- 45076 Semeru ceiling lamp LED silver', '915005694801', 1, 1, NULL, 1, NULL, NULL, NULL, 'Height-8.5 cm Length-51 cm Net weight-5.480 kg Width-51 cm', 'white', 'Dispersed from visible light, spectrum was the key inspiration behind the stellar design of the Philips Hue White ambiance Semeru LED small ceiling light. It’s a luminaire that surprises you with a hidden ambiance that adds to your bedroom. Dimmer switch included LED integrated Silver Smart control with Hue bridge*', 'Philips hue bridge required', '1 year', 'Lifetime up to-20,000 hour(s) Light source equivalent to traditional bulb of-245 W Total lumen output fixture-2400 lm Bulb technology LED-24 V Light color-2200-6500 Hue White Ambiance Mains power Range 220 V - 240 V-50-60 Hz Fixture dimmable-Yes LED-Yes Built in LED-Yes Energy class included light source-Built in LED Number of bulbs-1 Wattage bulb included-52 W Maximum wattage replacement bulb-52 W IP code-IP20 protection against objects bigger than 12.5 mm-no protection against water Class of protection-II - double insulated', 'Color-silver Material-metal synthetics Type-Ceiling light', NULL, 1500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(22, 'Philips- 45077 Semeru pendant LED silver', '915005694901', 1, 1, NULL, 1, NULL, NULL, NULL, 'Height maximum-150 cm Height minimum-60 cm Length-51 cm Net weight-5.400 kg Width-51 cm', 'white', 'Dispersed from visible light, spectrum was the key inspiration behind the stellar design of the Philips Hue White ambiance Semeru LED pendent light. It’s a luminaire that let you experience a general light with a surprising ambiance Dimmer switch inlcuded LED integrated Silver Smart control with Hue bridge*', 'Philips hue bridge required', '1 year', 'Lifetime up to-20,000 hour(s) Light source equivalent to traditional bulb of-245 W Total lumen output fixture-2400 lm Bulb technology - LED-24 V Light color-2200-6500 Hue White Ambiance Mains power-Range 220 V - 240 V-50-60 Hz Fixture dimmable-Yes LED-Yes Built in LED-Yes Energy class included light source-Built in LED Number of bulbs-1 Wattage bulb included-52 W Maximum wattage replacement bulb-52 W IP code-IP20 protection against objects bigger than 12.5 mm-no protection against water Class of protection-II - double insulated', 'Color-silver Material-metal synthetics Type-Suspension light', NULL, 1500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(23, 'Philips- 45078 Semeru wall lamp LED silver', '915005843701', 1, 1, NULL, 1, NULL, NULL, NULL, 'Height-4.8 cm Length-24.5 cm Net weight-0.960 kg Width-24.5 cm', 'white', 'Dispersed from visible light,spectrum was the key inspiration behind the stellar design of the Philips Hue White ambiance Semeru LED wall light. It’s a luminaire that surprises you with a hidden ambiance that adds to your moments LED integrated Silver Smart control with Hue bridge', 'Philips hue bridge required', '1 year', 'Lifetime up to-25,000 hour(s) Light source equivalent to traditional bulb of-122 W Total lumen output fixture-400 lm Bulb technology-LED-24 V Light color-2200-6500 Hue White Ambiance Mains power-Range 100 V - 240 V-50-60 Hz Fixture dimmable-Yes LED-Yes Built in LED-Yes Number of bulbs-1 Wattage bulb included-19 W Maximum wattage replacement bulb-19 W IP code-IP20 protection against objects bigger than 12.5 mm- no protection against water Class of protection-II - double insulated', 'Color-silver Material - metal synthetic Type- Wall light', NULL, 1500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(24, 'Philips- Adore Hue wall lamp chrome 1x40W 24V', '915005587401', 1, 1, NULL, 1, NULL, NULL, NULL, 'Height-6.4 cm Length-59.5 cm Net weight-0.680 kg Width-13.8 cm', 'chrome', 'Include this Philips Hue White ambiance Adore mirror light in your bathroom and experience light recipes that helps you energise, concentrate, read and relax. Use the dimmer switch and easily create the right light for all your moments Dimmer switch included LED integrated Chrome Smart control with Hue bridge*', 'Philips hue bridge required', '1 year', 'Lifetime up to-30,000 hour(s) Light source equivalent to traditional bulb of-204 W Total lumen output fixture-3000 lm Bulb technology - LED-24 V Light color-2200-6500 Hue White Ambiance Mains power-Range 100 V - 240 V-50-60 Hz Fixture dimmable-Yes LED-Yes Built in LED-Yes Energy class included light source-Built in LED Number of bulbs-1 Wattage bulb included-40 W Maximum wattage replacement bulb-40 W IP code-IP44 protection against objects bigger than 1 mm-protection from splashed water Class of protection-II - double insulated', 'Color-chrome Material - metal synthetics Type-Wall light', NULL, 1500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(25, 'Philips- Adore Hue wall lamp white 1x40W 24V', '915005630701', 1, 1, NULL, 1, NULL, NULL, NULL, 'Height-5.1 cm Length-56 cm Net weight-5.440 kg Width-56 cm', 'white', 'With the Philips Hue White ambiance Adore lighted mirror you can enjoy a beautiful light effect that prevents unwanted shadows. Use the dimmer switch to easily set the right light to help you energise, concentrate, read and relax Dimmer switch included LED integrated White Smart control with Hue bridge', 'Philips hue bridge required', '1 year', 'Lifetime up to-30,000 hour(s) Light source equivalent to traditional bulb of-204 W Total lumen output fixture-2400 lm Bulb technology- LED 24 V Light color- 2200-6500 Hue White Ambiance Mains power- Range 100 V - 240 V -50-60 Hz Fixture dimmable-Yes LED-Yes Built in LED-Yes Energy class included light source-Built in LED Number of bulbs-1 Wattage bulb included-40 W Maximum wattage replacement bulb-40 W IP code-IP44 protection against objects bigger than 1 mm-protection from splashed water Class of protection-II - double insulated', 'Color-white Material-metal Type-Wall light', NULL, 1500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(26, 'Philips- Adore Hue ceiling lamp chrome 1x40W 24V', '915005587301', 1, 1, NULL, 1, NULL, NULL, NULL, 'Height-6.0 cm Length-40.7 cm Net weight-2.280 kg Width-40.7 cm', 'white', 'Include a Philips Hue White ambiance Adore ceiling light in your bathroom and experience light recipes that helps you energize, concentrate, read and relax. Use the dimmer switch and easily create the right ambiance for all your moments Dimmer switch included LED integrated Chrome Smart control with Hue bridge*', 'Philips hue bridge required', '1 year', 'Lifetime up to-30,000 hour(s) Light source equivalent to traditional bulb of-204 W Total lumen output fixture-2400 lm Bulb technology-LED 24 V Light color-2200-6500 Hue White Ambiance Mains power- Range 100 V - 240 V 50-60 Hz Fixture dimmable-Yes LED-Yes Built in LED-Yes Energy class included light source-Built in LED Number of bulbs-1 Wattage bulb included-40 W Maximum wattage replacement bulb-40 W IP code-IP44 protection against objects bigger than 1 mm-protection from splashed water Class of protection-II - double insulated', 'Color-chrome Material- metal synthetics Type-Ceiling light', NULL, 1500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(27, '51107 Philips Hue DL WA 125mm 5\" downlights', '915005754401', 1, 1, NULL, 1, NULL, NULL, NULL, 'Cut out length-12.5 cm Cut out width-12.5 cm Length-15 cm Net weight-0.186 kg Recessed distance-6.5 cm Width-13.5 cm', 'white', 'This retrofit recessed downlight offers thousands of shades of white light at your fingertips. Control via Bluetooth to instantly turn on and off and the dim in one room, or pair with a Hue Bridge to unlock the full suite of features LED integrated High quality material Smart control with Hue bridge* Control with your voice*', 'Philips hue bridge required', '1 year', 'Lifetime up to-25,000 hour(s) Total lumen output fixture-600 lm Mains power-230 V Fixture dimmable-Yes LED-Yes Built in LED-Yes Energy class included light source-Built in LED Number of bulbs-1 Wattage bulb included-7 W Maximum wattage replacement bulb-7 W IP code-IP20 protection against objects bigger than 12.5 mm-no protection against water Class of protection-II - double insulated', '', NULL, 1500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(28, 'Koogeek LB1-1 Bulb', '', 2, 2, NULL, 2, NULL, NULL, NULL, 'Diameter: 2.36in / 60.00mm Height: 5.37in / 136.50mm Weight: 8.66oz / 245g', 'Multi colour - Offer 16 million colors to choose from and every color is dimmable in the Koogeek Home app, you can match different colors to create special atmospheres for every moment and personalize your home.', 'Koogeek Smart LED Light Bulb is a Wi-Fi enabled LED light bulb that uses only 8 watts and delivers up to 500 lumens of light with a color temperature from 2700K to 6500K. that works with Apple HomeKit.. Alexa. and google assitance Feature: High Brightness & 16 Million Colors, Works with Apple HomeKit and Support Siri Voice Control, Control Remotely via App, Support Color Changing and Brightness Adjustment, Create Scenes to Control Multiple Connected Light Bulbs, Schedule On/Off, Automate and Remotely Access. Both E26/E27 available.', 'Does not require any bridge. Connects to Wifi', '1 year', 'Material-Plastic and PBT Base Type-E26 (Medium screw base) and E27 (Medium screw base) Power input-120V AC, 60Hz 0.2A (Max.) and 200-240V AC, 50Hz 0.1A (Max.) Rated Power-8W Wattage Equivalence-60W (Max.) Color Temperature-2700K-6000K (warm white to daylight white) Rated Luminous Flux-500lm CRI-> 80 Compatibility-E26 and E27 light fittings Rated Lifetime-25,000 hours (22.8 years -- based on 3 hours use per day) Rated Beam Angle-Approx. 199.9° Home Wi-Fi-802.11b/g/n (2.4 GHz ONLY)', 'Package contents- Koogeek LB1 Smart Light Bulb / Quick Start Guide All Koogeek devices are Koogeek App Compatible', NULL, 1500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(29, 'Koogeek Doorc Contact and window sensor', 'DW1', 2, 2, NULL, 2, NULL, NULL, NULL, 'Magnet length: Approx. 26mm /1.02in Sensor length: Approx. 46mm /1.81in Magnet width: Approx. 12mm /0.47in Sensor width: Approx. 33mm /1.3in Magnet height: Approx. 9.2mm /0.36in Sensor height: Approx. 17.1mm /0.67in', 'Contact colour - white', 'Automatic Trigger Set up an automatic trigger to control other accessories. Easy Installation No need for cumbersome installation tools. Works with Apple HomeKit Use voice to control the product Remote Access Check the status of your home remotely', 'Does not require any bridge. Connects to Wifi', '1 year', 'Certificate-FCC, CE, RoHS, SRRC, UN38.3, MSDS Material-PC + ABS Power supply-1 * CR2450 3 V / 200 mAh cell battery LED indicator color-Green Wireless connection-Wireless 5.0 Operating temperature-10 ℃~60 ℃', 'Koogeek Door/Window Sensor Work with Apple HomeKit No Hub Required/ Replaceable Battery/ Remote Access/ Automatic Trigger/ for Doors Windows Cabinets and More/ White Package contents Koogeek DW1 Door & Window Sensor / Quick Start Guide All Koogeek devices are Koogeek App Compatible', NULL, 1500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(30, 'Yale Smart Lock Pro', '', 2, 2, NULL, 3, NULL, NULL, NULL, 'Dimensions: 3.4 x 2.2 x 3.4', '', 'Yale Smart Lock Pro is the ultimate lock for your smart home. It attaches to your existing deadbolt, on the inside of your door, so you can still use your keys. Yale Smart Lock Pro lets you securely lock and unlock the door with your phone, from anywhere. You can set it to automatically unlock when you arrive and lock when you leave. You can control your Yale Smart Lock Pro using your voice with Iphone, Apple Watch, Apple TV, HomePod, Ipad or just about any Apple device. ', 'Includes Yale Connect WiFi Bridge which connects your lock to the cloud, so you get full voice and remote access functionality right out of the box.', '1 year', 'tech spec in the form of PDF', 'Features: Total control -Lock and unlock your door, grant keyless access and keep track of who comes and goes, all from your Yale Access App. Upgrade your existing lock -Simply attach to your existing deadbolt from the inside of your door. Your existing keys will still working. Apple HomeKit enabled - Control your lock with your voice with an iPhone, AppleWatch, Apple TV, HomePod or iPad. Voice compatibility - Enable Siri to control or check status of your front door. Auto Unlock - Auto Unlock knows when you arrive and unlocks the door as you approach. Never fumble for keys again. Premium Design-Yale Smart Lock Pro is built with premium components and features LED lights and chime tones to complement your lock movement. Control guest access- Send guest secure keys to friends, family or people you trust instantly, all from the Yale Access app. Complete- Includes Yale Connect WiFi Bridge which connects your lock to the cloud, so you get full voice and remote access functionality right out of the box. Be sure its locked - Only Smart Lock Pro has DoorSenseTM, a sensor that tells you if your door is securely closed and locked. Auto Lock- Enable Auto Lock and never worry if your door is locked again.', NULL, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(31, 'Yale - YMF40 (Mortise Lock) Fingerprint, Pin Code, Mechanical Key & Remote Control (Optional)', '', 2, 2, NULL, 3, NULL, NULL, NULL, '', '', 'The Yale Digital Door Locks Collection! Smarter Solutions for your home. YMF40 is a Smart Digital Door Lock with multiple modes of access such as Biometric, PIN Code, Mechanical key & Remote Control (optional) and it comes with strong security features. 1 .Fingerprint 2. Mechanical Key 3. PIN Code 4.Work With App', '', '1 year', 'Technical details: Mortise Lock Type Up to 20 different fingerprint Up to 30 different user codes Mechanical Keys : 2 Keys Front Body 25 (D) X 66 (W) X 320 (H) mm Back Body 31 (D) X 66 (W) X 320 (H) mm Door Thickness : 40-110mm Wooden Doors Tech spec in the form of PDF', 'Features & Benefits: 3-in-one access lock (Fingerprint, PIN, & Mechanical Key) Remote control (Optional) Compatible with Z wave & Bluetooth (Optional) One-touch fingerprint verification with automatic cover (Easy Scan) Smart touchpad Automatic locking Low battery and emergency power Operation status notification Mechanical key override Safe handle Works with Video Door Phone ( For Video Door Phone configuration user would needYRM 20 N and YRM 20 AMC available under Accessory Section) Works with Yale Link App to access your lock remotely (To access Yale Link App function user would need Yale Link Bridge and Yale Link Bluetooth Module available under Accessory Section) Work with Yale Remote Control ( For Remote Control, user would need YRM 20 N and RC 100 available under Accessory Section)', NULL, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(32, 'Yale- YDR41 (Vertibolt Lock) Fingerprint & Pin Code', '', 2, 2, NULL, 3, NULL, NULL, NULL, '', '', 'The Yale Digital Door Locks Collection! Smarter Solutions for your home. YDR41 is a Smart Digital Door Lock with multiple modes of access such as Biometric, PIN Code.', '', '1 year', 'Technical Details: · Mortise Lock Type · Up to 20 unique fingerprints · Up to 30 unique user codes · Front Body 20 (D) X 64.6 (W) X 160.5 (H) mm · Back Body 35 (D) X 162.2 (W) X 87 (H) mm · Door Thickness : up to 55mm Wooden Doors', 'Features & Benefits: Access through Fingerprint and Pin One-touch fingerprint verification with automatic cover (Easy Scan) Lock Out Feature: After 5 unsuccesssful attempts on entering an invalid code or Fingerprint, 3 minute lockout mode would be activated Smart Etiquette: Door would be opened in the silent mode Intrusion/Damage Alarm High Temperature Alarm Fake Pin Code Internal Forced Lock Interlocking hook mechanism Smart touchpad Automatic locking Low battery and emergency power Operation status notification Double action open/close button Works with video door phone ( For Video Door Phone configuration user would needYRM 20 N and YRM 20 AMC available under Accessory Section) Works with Yale Link App to access your lock remotely (To access Yale Link App function user would need Yale Link Bridge and Yale Link Bluetooth Module available under Accessory Section) Work with Yale Remote Control ( For Remote Control, user would need YRM 20 N and RC 100 available under Accessory Section)', NULL, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(33, 'Yale - YDR 50G (Rim Lock) Fingerprint, Pin Code, Mechanical Key, Inbuilt YRM 20 Remote Control, APP Access (Optional)', '', 2, 2, NULL, 3, NULL, NULL, NULL, '', '', 'The Yale Digital Door Locks Collection! Smarter Solutions for your home. YDR 50G is a Smart Digital Door Lock with multiple modes of access such as Fingerprint, PIN Code, Mechanical key & Remote Control (optional) and it comes with strong security features. Product Key Features 1.Card Key 2.Fingerprint 3.Mechanical Key 4.PIN Code 5.Work With App Your fingerprint is the Key!!!', 'Yale YDR 50G gives user all the access capabilities and works with Yale Bridge, which enables user to open lock remotely from any location', '1 year', 'Technical details: Rim Lock Type Up to 20 different fingerprint Up to 30 different user codes Mechanical Keys : 2 Keys Front Body 28 (D) X 63.5 (W) X 176 (H) mm Back Body 40 (D) X 77 (W) X 220 (H) mm Door Thickness : 40-65mm Wooden Doors', 'Features & Benefits: 5 in 1 Access Lock (Fingerprint, PIN, RFID ,Remote Control & Mechanical Key) Remote Control RC100 is a part of the package, as YRM 20 module is in-built Compatible with Z wave & Bluetooth (Optional) One-touch fingerprint verification with automatic cover (Easy Scan) Smart Etiquette – enter pin codes on the keypad and open the door lock in silent mode In-built magnetic sensor for automatic locking Low Battery and emergency power Operation status notification Mechanical key override 80db alarm ( Break/ Damage /Fire) Works with Video Door Phone ( For Video Door Phone configuration user would need YRM 20 N and YRM 20 AMC available under Accessory Section) Works with Yale Link App to access your lock remotely (To access Yale Link App function user would need Yale Link Bridge and Yale Link Bluetooth Module available under Accessory Section) Work with Yale Remote Control (For Remote Control, user would need YRM 20 N and RC 100 available under Accessory Section)', NULL, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(34, 'Yale - YDM7116 (Mortise Lock) Fingerprint, PIN Code, RFID Card, Mechanical Key & Bluetooth (BLE), Remote Control (Optional)', '', 2, 2, NULL, 3, NULL, NULL, NULL, '', '', 'The Yale Digital Door Locks Collection! Smarter Solutions for your home. YDM7116 is a Smart Digital Door Lock with multiple modes of access such as Fingerprint, PIN Code, RF Card, Mechanical key & Bluetooth, Remote Control (optional) and it comes with strong security features. Your fingerprint is the Key!!! Product Key Features 1.Card Key 2.Fingerprint 3.Mechanical Key 4.PIN Code 5.Work With App', 'Yale YDM 7116 gives user all the access capabilities and works with Yale Bridge which enables user to open lock remotely from any location', '1 year', 'Technical Details: Mortise Lock Type Up to 20 different fingerprint Up to 30 different user codes Mechanical Keys : 2 Keys Front Body 40 (D) X 68 (W) X 340 (H) mm Back Body 38 (D) X 72 (W) X 344 (H) mm', 'Features & Benefits: 5-in-one to access the lock Remote control (Optional) Compatible with Z wave & Bluetooth One-touch fingerprint verification (Easy Scan) Smart touchpad Automatic Locking Low Battery and emergency power Operation status notification Mechanical key override Safe handle Works with Video Door Phone ( For Video Door Phone configuration user would need YRM 20 N and YRM 20 AMC available under Accessory Section) Works with Yale Link App to access your lock remotely (To access Yale Link App function user would need Yale Link Bridge and Yale Link Bluetooth Module available under Accessory Section) Work with Yale Remote Control (For Remote Control, user would need YRM 20 N and RC 100 available under Accessory Section)', NULL, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(35, 'Yale - YDME100 (Mortise Lock) Fingerprint, Pin Code & Mechanical Key', '', 2, 2, NULL, 3, NULL, NULL, NULL, '', '', 'YDME-100 is enables user with Fingerprint, Pin Code & Mechanical Key Product Key Features 1.Fingerprint 2.Mechanical Key 3.PIN Code', '', '1 year', 'Technical Details: Mortise Lock Type Fingerprint Up to 100 User Codes Up to 100 Mechanical Keys : 3 Keys Door Thickness : 40mm - 70mm', '3-in-one Access Lock (Fingerprin, PIN, & Mechanical Key) Mechanical Key Override Temporary Construction Keying', NULL, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(36, 'Yale- YMI70 Push Pull (Mortise Lock) Fingerprint, Pin Code, RFID Card, Mechanical Key & Bluetooth (BLE), Remote Control (Optional)', '', 2, 2, NULL, 3, NULL, NULL, NULL, '', '', 'The Yale Digital Door Locks Collection! Smarter Solutions for your home. YMI70 is a Smart Digital Door Lock with multiple modes of access such as Single Push Action, Fingerprint, PIN Code, RF Card, Mechanical key & Smart Connectivity: Bluetooth, Z-Wave and Wi-Fi, Remote Control (optional) and it comes with strong security features.', '', '1 year', 'Technical Details: Mortise Lock Type Up to 40 different fingerprint Up to 30 different user codes Up to 40 User Card Mechanical Keys : 2 Keys Front Body 77(W) X 397.4(H) X 71.4(D) mm Back Body 77(W) X 396.7(H) X 78(D) mm', 'Features & Benefits: 5-in-one to access the lock Remote control (Optional) Compatible with Z wave & Bluetooth One-touch fingerprint verification (Easy Scan) Smart touchpad Automatic Locking Low Battery and emergency power Alarm (Break-in / Damage) Mechanical key override Fake PIN Code', NULL, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(37, 'Yale-YDME 90 (Mortise Lock) Fingerprint, Pin Code, RF Card & Mechanical Key', '', 2, 2, NULL, 3, NULL, NULL, NULL, 'YDME90.pdf', '', 'The Yale Digital Door Locks Collection! Smarter Solution for your home. YDME-90 is an advanced four in one access Smart Digital Door Lock with strong security features. Product Key Features 1.Card Key 2.Fingerprint 3.Mechanical Key 4.PIN Code', '', '1 year', 'Technical Details: Mortise Lock Type Fingerprint Up to 37 User Codes Up to 78 RFID Cards Up to 30 Mechanical Keys : 3 Keys Front Body 32.6 mm (D) X 73.8 mm (W) X 322 mm (H) Back Body 30 mm (D) X 78.6 mm (W) X 327 mm (H) Door Thickness : 35 mm -55mm', 'features and Benefits : Yale YDME-90 is enables user with Fingerprint, Card, Pin and Key. 4-in-one Access Lock (Fingerprin, PIN, RF Card & Mechanical Key) LCD Screen – Displays date, time, user ID access and audit trail Low Battery and emergency access Anti-panic Egress Mechanical Key Override Internal Forced lock Hidden Key Hole High Quality SS Finish Lowe Battery Indicator Integration with Video Door Phone (Wired)', NULL, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(38, 'Yale-YDME80 (Mortise Lock) Fingerprint, Pin Code, & Mechanical key', '', 2, 2, NULL, 3, NULL, NULL, NULL, 'YDME80.pdf', '', 'The Yale Digital Door Locks Collection! Smarter Solutions for your home. YDME80 (Mortise) is a Smart Digital Door Lock with multiple modes of access such as Biometric, PIN Code, Mechanical key and it comes with strong security features. Product Key Features 1.Fingerprint 2.Mechanical Key 3.PIN Code', '', '1 year', 'Technical Details: Mortise Lock Type Register Up to 32 fingerprints Register Up to 32 Pin Codes Mechanical Keys : 3 Keys Front Body 22.5 mm (D) X 72.9 mm (W) X 310 mm (H) Back Body 26 mm (D) X 75 mm (W) X 310.4 mm (H) Door Thickness : 35-55 mm Wooden/Metal Doors', 'Features & Benefits: 3-in-one Access Lock (Fingerprint, PIN & Mechanical Key) Smart touchpad Automatic Locking Low Battery and Emergency Power Operation status notification Mechanical Key override Anti-Panic egress Fake Pin Code English Voice Guide Alrarm: Breakage/Damage Integration with Video Door Phone (Wired)', NULL, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(39, 'Yale-YDME70 (Mortise Lock) Pin Code, RF Card, & Mechanical Key', '', 2, 2, NULL, 3, NULL, NULL, NULL, 'YDME70.pdf (.pdf, 1.7 MB)', '', 'The Yale Digital Door Locks Collection! Smarter Solutions for your home. YDME70 (Mortise) is a Smart Digital Door Lock with multiple modes of access such as RF Card, PIN Code, Mechanical key and it comes with strong security features. Product Key Features 1.Card Key 2.Mechanical Key 3.PIN Code', '', '1 year', 'Technical Details: Mortise LockType Register Up to 32 RFID Cards Register Up to 32 Pin Codes Mechanical Keys: 3Keys Front Body : 22.5 mm (D) X 73 mm (W) X 310 mm (H) Back Body : 26 mm (D) X 75 mm (W) X 310.4 mm (H) Door Thickness : 35-55mm Wooden/Metal Doors', 'Features & Benefits: 3-in-one Access Lock (PIN, RF Card & Mechanical Key) Smart touchpad Automatic Locking Low Battery and emergency power Operation status notification Mechanical Key override Anti-Panic egress Fake Pin Code English Voice Guide Alrarm: Breakage/Damage Integration with Video Door Phone ( Wired)', NULL, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(40, 'Yale-YDME50 (Dead Latch Lock) Pin Code, RF Card, & Mechanical Key', '', 2, 2, NULL, 3, NULL, NULL, NULL, 'YDME50.pdf (.pdf, 6.5 MB)', '', 'The Yale Digital Door Locks Collection! Smarter Solutions for your home. YDME50 (Dead Lock) is a Smart Digital Door Lock with multiple modes of access such as PIN Code, RF Card, & Mechanical key and it comes with strong security features. Product Key Features 1.Card Key 2.Mechanical Key 3.PIN Code', '', '1 year', 'Technical Details: Dead Latch Lock Type Register Up to 30 RFID Cards Register Up to 78 Pin Codes Mechanical Keys : 2 Keys Front Body 37.97 mm (D) X 70 mm (W) X 170 mm (H) Back Body 25.48 mm (D) X 70 mm (W) X 179 mm (H) Door Thickness : 35-55mm Wooden Doors', 'Features & Benefits: 3-in-one Access Lock (PIN, RF Card & Mechanical Key) Low Battery and emergency power Mechanical key override Anti-panic egress', NULL, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(41, 'Yale-YDD424 (DeadBolt Lock) Fingerprint, Pin Code, Mechanical Key & Remote Control', '', 2, 2, NULL, 3, NULL, NULL, NULL, 'YDD424.pdf', '', 'The Yale Digital Door Locks Collection! Smarter Solution for your home. High-tech Proximity Card Digital Door Lock with strong security features. Product Key Features 1.Fingerprint 2.Mechanical Key 3.PIN Code 4.Work With App', 'YDD 424 gives user all the access capabilities and works with Yale Bridge, which enables user to open lock remotely from any location', '1 year', 'Technical Details: DeadBolt lock Type Pin code: 6-12 digits Finish: Champagne Gold Front Body: 31.5 mm (D) X 66 mm (W) X 176 mm (H) Back Body: 35 mm (D) X 70 mm (W) X 170 mm (H) Door Thickness : Suitable for 35-55 mm Wooden Doors', 'Features & Benefits: One-touch fingerprint verification method PIN Code/Mechanical key override Tubular deadbolt Lock controller Inside for safe access –ibutton Remote control (Optional) Champagne Gold Finish Voice guide feature Smart touchpad Automatic locking Break-in/damage alarm Low battery alarm and emergency power supply Works with Video Door Phone ( For Video Door Phone configuration user would need YRM 20 N and YRM 20 AMC available under Accessory Section) Works with Yale Link App to access your lock remotely (To access Yale Link App function user would need Yale Link Bridge and Yale Link Bluetooth Module available under Accessory Section) Work with Yale Remote Control ( For Remote Control, user would need YRM 20 N and RC 100 available under Accessory Section)', NULL, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(42, 'Yale-YDR414 (Rim Lock) Fingerprint, Pin Code, Mechanical Key & Remote Control (Optional)', '', 2, 2, NULL, 3, NULL, NULL, NULL, 'YDR414_Leaflet.pdf (.pdf, 3.5 MB)', '', 'The Yale Digital Door Locks Collection! Smarter Solution for your home. High-tech Proximity Card Digital Door Lock with strong security features. Product Key Features 1.Fingerprint 2.Mechanical Key 3.PIN Code 4.Work With App', 'YDR 414 gives user all the access capabilities and works with Yale Bridge, which enables user to open lock remotely from any location', '1 year', 'Technical Details: Rimlock Type Pin code: 6-12 digits Color:Black Front Body: 31.5 mm (D) X 66 mm (W) X 176 mm (H) Back Body: 46 mm (D) X 76 mm (W) X 201 mm (H) Door Thickness : Suitable for 35-55mm Wooden Door', 'Features & Benefits: First Smart Door Lock in India with maid function ( Maid function restricts the non desirable entry and exit of house help) Yale YDR 414 is the only Smart Lock which gives \" Open Door\" Alert i.e. if door is not closed within 1 minute it will initiate an alarm One-touch fingerprint verification method. PIN Code/Mechanical key override Remote control (Optional) SS 304 Deadbolt Lock controller inside for safe access - ibutton Voice guide feature Smart touchpad Automatic locking Break-in/damage alarm Low battery alarm and emergency power supply Works with Video Door Phone ( For Video Door Phone configuration user would need YRM 20 and YRM 20 AMC available under Accessory Section) Work with Yale Remote Control ( For Remote Control, user would need YRM 20 and RC 100 available under Accessory Section)', NULL, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `products` (`id`, `name`, `material_no`, `concept_id`, `cat_id`, `sub_cat_id`, `brand_id`, `type_id`, `compatibility_id`, `power_consumption_id`, `physical_spec`, `light_color`, `introduction`, `accessories_required`, `warranty`, `technical_spec`, `additional_features`, `wired_wireless`, `price`, `igst`, `sgst`, `transit`, `additional_properties`, `created_at`, `updated_at`, `deleted_at`) VALUES
(43, 'Yale-YDM4109 (Mortise Lock) Fingerprint, Pin Code, Mechanical Key & Remote Control (Optional)', '', 2, 2, NULL, 3, NULL, NULL, NULL, 'YDM4109.pdf', '', 'The Yale Digital Door Locks Collection! Smarter Solution for your home. High-tech Fingerprint Digital Door Lock with strong Security features. Product Key Features 1.Fingerprint 2.Mechanical Key 3.PIN Code 4.Work With App', 'Yale YDM 4109 gives user all the access capabilities and works with Yale Bridge which enables user to open lock remotely from any location', '1 year', 'Technical Details: Mortise Lock Type Fingerprint: Up to 20 Mechanical Keys: 2 Keys Pin Code: 6-12 digits Colour: Black/Silver/Golden Front Body : 28 mm ( D) X 76.6 mm (W) X 334.6mm (H) (w/o lever) Back Body : 35mm (D) X 76.6 mm (W) X 304.6 mm (H) (w/o lever) Thickness : Suitable for 40-80 mm thick timber doors Backset : 60mm', 'Features & Benefits: One touch fingerprint verification method Automatic locking Voice guide feature Smart touchpad Lock Out Feature: After 5 unsuccessful attempts on entering an invalid code or Fingerprint, 3 minute lockout mode would be activated Intrusion/Damage Alarm High Temperature Alarm Internal Forced Lock Fake Pin Code Easy registration of Fingerprint Emergency over-ridekey Anti-panic egress with safe handle Automatic alarm (Break-in/Damage) Low-battery alarm and emergency power supply terminal Works with Video Door Phone ( For Video Door Phone configuration user would need YRM 20 N and YRM 20 AMC available under Accessory Section) Works with Yale Link App to access your lock remotely (To access Yale Link App function user would need Yale Link Bridge and Yale Link Bluetooth Module available under Accessory Section) Work with Yale Remote Control (For Remote Control, user would need YRM 20 N and RC 100 available under Accessory Section', NULL, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(44, 'Yale-YDM3109 (Mortise Lock) Pin Code, Proximity Card Key, Mechanical Key & Remote Control (Optional)', '', 2, 2, NULL, 3, NULL, NULL, NULL, 'YDM3109-Digital-Lock-Card-Lock-Catalog.pdf (.pdf, 881 kB)', '', 'The Yale Digital Door Locks Collection! Smarter Solution for your home. High-tech Proximity Card Digital Door Lock with strong security features.', '', '1 year', 'Technical Details: Mortise Lock Type Type Promixity Cards: 4 (Up to 40 cards) Mechanical keys: 2 Keys Pin code: 6-12 digits Color: Silver/Golden Outside trim dimension : 27mm X 68.6mm X 306.6mm (w/o lever) Thickness : Suitable for 40-80mm thick wooden doors Backset : 60mm', 'Features & Benefits: Proximity card identification Easy registration of keys Missing key invalidation Scramble code Mechanical cylinder applied Break-in damage alarm Automatic lock mode Electronic shock resistance Remote control (Optional)', NULL, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(45, 'Yale-YDM3212 (Clutch Mechanism) Pin Code, Proximity Card Key & Remote Control (Optional)', '', 2, 2, NULL, 3, NULL, NULL, NULL, 'YDM3212-Yale-Card-Key-Keypad-Digital Door Lock-Catalog.pdf (.pdf, 1.4 MB)', '', 'The Yale Digital Door Lock Collection Smarter Solution for your home High tech Proximity card Digital Door Lock with strong features', '', '1 year', 'Technical Details: Clutch Mechanism Pin code: 4-12 digits Type Promixity Cards: 4 (Up to 20 cards) Color: Wine Red Front Body Dimension : 24.5 (D) X 74 (W) X 200 (H) mm Back Body Dimension : 30 (D) X 74 (W) X 200 (H) mm Thickness : 38-55mm Backset : 70mm', 'Features & Benefits: Various access (PIN Code & Proximity Card Key) Smart Touchpad Operation Status Notification Anti-panic egress Missing card key invalidation Automatic Locking (Clutch Mechanism) Break-in damage alarm Automatic lock mode', NULL, 2500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(46, 'Yale-YDR4110 (Rim Lock) Fingerprint, Pin Code & Remote Control (Optional)', '', 2, 2, NULL, 3, NULL, NULL, NULL, 'YDR4110.pdf', '', 'The Yale Digital Door Lock Collection Smarter Solution for your home High tech Finger Print Access Digital Door Lock with strong features Product Key Features 1.Fingerprint 2.PIN Code 3.Work With App', 'YDR 4110 works with Yale Bridge, which enables user to open lock remotely from any location', '1 year', 'Technical Details: Rimlock Type Pin code: 6-12 digits Color: Black Front Body : 20 mm ( D) X 64.6 mm (W) X 160.5 mm (H) Back Body : 36.4 mm (D) X 142.1mm (W) X 87.1 mm (H) Door Thickness : Suitable for 35-55 mm steel and wooden door', 'Features & Benefits: One-touch Fingerprint Verification Method Voice Guide Feature Smart Touchpad Automatic Locking Break-in/damage alarm Low battery alarm and Emergency Power Supply Remote Control (Optional) Works with Video Door Phone ( For Video Door Phone configuration user would need YRM 20 N and YRM 20 AMC available under Accessory Section) Works with Yale Link App to access your lock remotely ( To access Yale Link App function user would need Yale Link Bridge and Yale Link Bluetooth Module available under Accessory Section) Work with Yale Remote Control ( For Remote Control, user would need YRM 20 N and RC 100 available under Accessory Section)', NULL, 2500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(47, 'Yale-YDR3110 (Rim Lock) Pin Code, RF Card Key & Remote Control (Optional)', '', 2, 2, NULL, 3, NULL, NULL, NULL, 'YDR 3110 Digital Rim Lock catalog.pdf', '', 'The Yale Digital Door Lock Collection, Smarter Solution for your home with High-Tech Proximity cards Digital Door Lock with strong features', '', '1 year', 'Technical details: Rim lock Type Pin code: 6-12 digits Color: Black Outside trim dimension : 19mm X 65mm X 160mm Door Thickness : suitable for 45-55mm steel and wooden door. Backset : 60-90mm', 'Features & Benefits: Pin Code or RF Card Key Access Smart Touchpad Automatic Locking Break-in/damage alarm Low battery alarm and Emergency Power Supply Remote Control (Optional)', NULL, 2500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(48, 'Yale-YDR343 (Vertical Rim Lock with Mobile Access) RF Smart Chip, Touch Keypad & Remote Control (Optional)', '', 2, 2, NULL, 3, NULL, NULL, NULL, 'YDR343.pdf', '', 'The Yale Digital Door Locks Collection! Smarter Solution for your home. World\'s Slimmest Digital Door Lock with strong Security features. Product Key Features 1.Card Key 2.PIN Code', '', '1 year', 'Technical Details: Pin Code: 4-12 digits Emergency Power Supply Front Body Dimension: 11 mm (D) x 68 mm (W) x 179 mm (H) Back Body Dimension: 48.8 mm (D) x 77.5 mm (W) x 190.5 mm (H)', 'Features & Benefits: World\'s Slimmest Digital Door Lock (11mm Super Slim Design) Various Access (RF Smart Chip, Touch Keypad (Remote Control - Optional) Modern & Slim Design Safe Thumb-Turn Missing Key Invalidation High Temperature Alarm Fake PIN Code Works with Video Door Phone ( For Video Door Phone configuration user would need YRM 20and YRM 20 AMC available under Accessory Section) Work with Yale Remote Control ( For Remote Control, user would need YRM 20 and RC 100 available under Accessory Section)', NULL, 2500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(49, 'Yale - YDG313 (Rim Lock for Glass Doors) Pin Code, RF Card Key & Remote Control (Optional)', '', 2, 2, NULL, 3, NULL, NULL, NULL, 'YDG313_Leaflet.pdf (.pdf, 816 kB)', '', 'YDG313 (Rim Lock for Glass Doors) Pin Code, RF Card Key & Remote Control (Optional)', '', '1 year', 'Technical Details: Pin Code: 4-12 digits Color: Mirror Finish Front Body Dimension: 36(D) x 72(W) x 185(H) mm Back Body Dimension: 13(D) x 66(W) x 179(H) mm', 'Features & Benefits: Various Access (PIN Code or RF Card Key, Remote control-optional) Magic Mirror Safe Thumb-Turn Clip Type Bracket (Can be installed on Glass Doors of 9-13mm thickness) High Temperature Alarm Fake PIN Code Advanced Mode Visitor Code (Unique one-time visitor code which lapses after single operation)', NULL, 2500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50, 'Yale - YDR323 (Vertical Rim Lock for Wooden Doors) Pin Code, RF Card Key & Remote Control (Optional)', '', 2, 2, NULL, 3, NULL, NULL, NULL, 'YDR323_Leaflet.pdf (.pdf, 816 kB)', '', 'YDR323 (Vertical Rim Lock for Wooden Doors) Pin Code, RF Card Key & Remote Control (Optional)', '', '1 year', 'Technical Details: Pin Code: 4-12 digits Color: Mirror Finish Front Body Dimension: 36(D) x 72(W) x 185(H) mm Back Body Dimension: 13(D) x 66(W) x 179(H) mm', 'Features & Benefits: Various Access (PIN Code or RF Card Key, Remote control-optional) Magic Mirror Safe Thumb-Turn High Temperature Alarm Fake PIN Code Advanced Mode Visitor Code (Unique one-time visitor code which lapses after single operation)', NULL, 2500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(51, 'CPVan Smart WIFI RGB Bulb 7.5W', 'CP-Q0', 1, 1, NULL, 4, NULL, NULL, NULL, '', 'Multi Coloured RGB Light', 'Smart Wifi RGB Bulb. 1. Light up your home in advance through APP . 2.Connect the smart LED Bulb to amaon Alexa or Google Homes for voice control 3.Save upto 60% of energy when compared to an incandescent light 4. Customize your romantic smart scnes 5.16 Million Colours 6. Smart Timer Setting', '', '1 year', 'Base Type - E26/E27/B22 LED Beads- 26 Pcs Colour temp = 6500k+RGB Luminous Flux - 750 LM CRI - >_ 80 Power Output - 7.5 W Power Factor - >0.5 Input Voltage - AC 100 - 240 V, 50-60MHz Working time - 25,000 hours Encryption type - WEP/TKIP/AES Working temp- -20 to 50 C Storage temperature - -40 ~80 C', '◎ AC 100-240V power supply, Max. Output 7.5W ◎ Base Type: E26/E27 ◎ Color Temperature : 6500K+RGB(16 million color lights) ◎ 750LM Luminous Flux ◎ Colour, brightness, colour temperature can be changeable by phone App ◎ Works with Google home/ Amazon Alexa/ IFTTT', NULL, 2500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(52, 'CPVan Smart RGB Bulb 10W', 'CP-Q9', 1, 1, NULL, 4, NULL, NULL, NULL, '', 'Multi Coloured RGB Light', 'Smart Wifi RGB Bulb. 1. Light up your home in advance through APP . 2.Connect the smart LED Bulb to amaon Alexa or Google Homes for voice control 3.Save upto 60% of energy when compared to an incandescent light 4. Customize your romantic smart scnes 5.16 Million Colours 6. Smart Timer Setting', '', '1 year', 'Base Type - E26/E27 LED Beads- 26 Pcs Colour temp = 6500k+RGB Luminous Flux - 900LM CRI - >_ 80 Power Output - 10W Power Factor - >0.5 Input Voltage - AC 100 -240 V, 50-60MHz Working time - 25,000 hours Encryption type - WEP/TKIP/AES Working temp- -20 to 50 C Storage temperature - -40 ~80 C', '◎ AC 100-240V power supply, Max. Output 10W ◎ Base Type: E26/E27 ◎ Color Temperature : 6500K+ RGB(16 million color lights) ◎ 900LM Luminous Flux ◎ Colour, brightness, colour temperature can be changeable by phone App ◎ Works with Google home/ Amazon Alexa/ IFTTT', NULL, 2500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(53, 'CPVan BR30 Smart RBG Bulb', 'CP- Q10CWM', 1, 1, NULL, 4, NULL, NULL, NULL, '', 'Multi Coloured RGB Light with cold and warm white', 'Smart Wifi RGB Bulb. 1. Light up your home in advance through APP . 2.Connect the smart LED Bulb to amaon Alexa or Google Homes for voice control 3.Save upto 60% of energy when compared to an incandescent light 4. Customize your romantic smart scnes 5.16 Million Colours 6. Smart Timer Setting', '', '1 year', 'Base Type - E26/E27 Beads type- RGB-3030/W-2835 Colour temp = 2700-9000K+RGB Luminous Flux - 700-800LM CRI - > 80 Power Output -13W Power Factor - >0.5 Input Voltage - AC 100 -240 V, 50-60MHz Working time - 25,000 hours Encryption type - WEP/TKIP/AES Working temp- -20 to 50 C Storage temperature - -40 ~80 C Housing material- PC fireproof materials', '◎ AC 100-240V power supply, Max. Output 9W ◎ Base Type: E26/E27 ◎ BR30 type ◎ Color Temperature : 2700-6500K& RGB full color ◎ 720LM Luminous Flux ◎ Colour, Brightness, cold&warm colour can be changeable by phone APP ◎ Works with Google home/ Amazon Alexa/ IFTTT', NULL, 2500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(54, 'CPVan 1080P HD Indoor Camera', 'CP- IPCAM01PT', 2, 2, NULL, 4, NULL, NULL, NULL, '', '', 'Smart 1080P Tilt/pan IP Camera 1.360 degree Panoroma 2. Motion Detection 3.Night Vision 4.two Way Audio 5. Device Sharing', '', '1 year', 'Image Sensor - 1/3 High Definition Colour CMOS Resolution- 1920*1080 Pixel- 2MP Compression Format:H.264 Lens: 3.6mm Pan/Title: Horizontal 365 degree,Vertical 110 degree Detection Alarm: Notification push with alarm tome, 30s alert video push Two way audio: support Support Micro-SD card storage: Up to 128 GB Motion Detection: Support Angle vision: 75 degree Power supply:DC 5V 1A Night Vision:10m', '◎ Works with Google Home/ Alexa ◎ Pan-tilt WIFI camera with panoramic viewing angles ◎ 355° horizontal field of view with smart tracking ◎ Remote monitoring via phone APP ◎ Feedback and record video when any motion is detected ◎ Two-way audio supported, Night vision supported', NULL, 2500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(55, 'CPVan 1080P HD Outdoor Camera', 'CP-IP6S', 2, 2, NULL, 4, NULL, NULL, NULL, '', '', 'Smart 1080P Outdoor Bullet Camera 1. Motion Detection 2.Night Vision 3. Water Proof 4.Supports Amazon Alexa 5. 2 way audio', '', '1 year', 'View Angle: 80 Degree Resolution- 1920*1080 Image Sensor :1/2.7 CMOS Pixel- 2MP Compression Format:H.264 High profile NIght Vision Distance:25M Water proof Level: IP66 Local Storage: Micro SD card, Max 64GB Power Input: 12V 1A Wireless standard: 2.4G only Working humidity: 10%~90% Working Temperature: -4F to 131F', '◎ 2MP high-resolution lens and wide 80° viewing angle ◎ Remote monitoring via Smart Life APP ◎ Two-Way Audio & Cloud Storage ◎ Feedback and record video when any motion is detected ◎ Nght vision supported ◎ IP66 Waterproof ◎ Works with Echo Show', NULL, 2500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(56, 'CPVan1080P HD Battery Camera', 'CP- BODRIPC 3S', 2, 2, NULL, 4, NULL, NULL, NULL, '', '', '100% Wire free Battery Powered Camera 1. Wireless Intuitive Outdoor and Indoor Camera 2.Motion Activated Alerts 3. 2 way Audio 4.Night Vision 5.IP65 Waterproof', '', '1 year', 'Dimension: 90mm*81mm Battery: Rechargable (2*18650) Visual Angle : Diagonal 104 degree Resolution: 1920*1080 Pixel:2MP Image Sensor:1080P CMOS sensor Wake up duration: WIthin 600ms Wake up method: PIR human body induction/Phone active Infrared Light: 6*850mm NIght vision distance:5M Waterproof level: IP65 Local Storage: TF card, support Max 32GB Wireless Standard:802.11b/g/n Working Current:200ma standby current : 160uA', '◎ 100% wire free smart camera with rechargeable battery ◎ 1080p video resolution is complimented ◎ Remote monitoring via Smart Life APP ◎ Two-Way Audio & Cloud Storage ◎ Feedback and record video when any motion is detected ◎ Night vision supported', NULL, 2500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(57, 'CPVan Smart Video Doorbell', 'CP-VD7P', 2, 2, NULL, 4, NULL, NULL, NULL, '', '', 'Smart Video Doorbell - Watch, Speak, Notification Not only a Doorbell, but also a Monitor 2 way Communication 166 Super wide angle Motion Activated Alerts Infrared Night Vision', '', '1 year', 'Dimension: 137*67*30mm Battery: Rechargable (2*18650) Visual Angle : 166 degree Resolution: 1080*720 Pixel:1MP Image Sensor:1/2.7\" CMOS sensor Wake up duration: WIthin 600ms Wake up method: PIR human body induction/Phone active / Press Button Infrared Light: 6*850mm NIght vision distance:5M Waterproof level: IP65 Local Storage: TF card, support Max 32GB Working Current:170ma standby current : 160uA', '◎ 1MP high-resolution 720P ◎ Low power smart video doorbell ◎ Support PIR motion detection ◎ Support mobile phone & button & PIR detection wake up ◎ High Quality two-way talk voice with noise cancellation ◎ Day and night mode automatic switching ◎ Image adjustment, automatic white balance, Back light compensation ◎ Infrared LED: 6 IR LEDs, night visibility up to 5 meters', NULL, 2500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(58, 'CPVan Smart IR Controller', 'CP-IR01', 3, 3, NULL, 4, NULL, NULL, NULL, '', '', 'WIFI IR CONTROLLER - Control your IR Appliances from anywhere. Say goodbye to your dozens of remotes . Now you can combine the remotes fo infrared home applinaces in ne CPVan IR Controller, including your Air Conditioner, Tv, TV Box and more . 1.Smart Timer Schedule 2.Scene Linkage with other CPVan Devices', '', '1 year', 'Dimension- 70*70*24mm Power Supply- 5V 1A Wireless Consumption- <=0.3W WIFI Standard - 2.4GHzb b/g/n Encryption-WEP/TKP/AES Infrared Frequency- 38KHz Working Temperature - -24 ~ 40 Degree C Working Humdity - <=80%', '◎ Support multi-brand and multi-type infrared products, with massive remote control code base. ◎ 360 degree cover, long distance control up to 8m. ◎ IR and WiFi module built-in ◎ APP remote control ◎ Alexa and Google Home voice control', NULL, 2500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(59, 'CPVan PIR Motion Sensor', 'CP- MD08W', 2, 2, NULL, 4, NULL, NULL, NULL, '', '', 'Smart WIFI PIR Motion Sensor: 1.Mobile APP Notification 2.110 degree wide angle 3. Intelligent Linkage to Smart Devices. 4.Infrred Human body detection 5.One button arm,real time alarm 6.Low Battery notification', '', '1 year', 'Imput Voltage: DC3V CR 123A Quiescent current: < 45 uA Alarm current:<160mA Low power under voltage: <2.6V Wifi: 802.11b/g/n Detection distance: 10M Distance angle: 110 Degree Installation method: Bracket mounting Operating temperature: -10-50C Working humidity: Up to 95% RH', '◎ Get alerted if someone is moving in your house ◎ 110°detect angle and 10 meters distance ◎ Link with more lighting, security and control devices ◎ Ultra low power consumption, Low battery reminder ◎ Free tool installation', NULL, 2500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(60, 'CPVan Door& Window Sensor', 'CP- WD11W', 2, 2, NULL, 4, NULL, NULL, NULL, '', '', 'Smart WIFI PIR Motion Sensor: 1.Mobile APP Notification 2. Intelligent Linkage to Smart Devices. 3. Low Battery notification When you leave home, it will oush notification to you if the door/window are open or invaded by external objects, you will find anomolies in your home immediately.', '', '1 year', 'Input Voltage: DC 3V (LR03 AAA Battery *2 ) Power Consumption: <1uA Alarm current: <160mA Stand by current: <2uA Alarm current:<100mA Low Battery Alarm: 2.4V Wifi standard:2.4G Magnetic control distance:>2.5mm Working temperature: 0-55degree Working humidity: Up to 95% RH', '◎ Get alerted if the door or window is opened ◎ Link with more lighting, security and control devices ◎ Ultra low power consumption, Low battery reminder ◎ Battery capacity showing on the APP ◎ Free tool installation', NULL, 2500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(61, 'CPVan WIFI Smoke Alarm', 'CP- SM05W', 2, 2, NULL, 4, NULL, NULL, NULL, '', '', 'Wifi Smoke Detctor : It will alarm loudly when it detects smoke in your house, push the message to you via phone app, and remotely remind you to take actions . 1. Live strobe and sound alarm 2. App push 3.Monitoring centre push 4.Easy to install.', '', '1 year', 'Dimension: 10.7R*4.8H(cm) Power Supplu: DC9V alkaline battery (6LR61) Static current: <10uA Alarm current:<100mA Detcting area: 20m sq. Alarm sound: >80dB Low battery alert: <7.0V+/- 0.2V Working temperature: 0 degree C ~ +50 degree C Working Humidity: <95%RH, no freezing', '◎ Auto-rest after smoke clearing ◎ Self-test button ◎ Red led light indication ◎ Live strobe and sound alarm notification ◎ Low battery alert ◎ Low power consumption', NULL, 2500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(62, 'CPVan Water Leak Detector', 'CP- WL01W', 2, 2, NULL, 4, NULL, NULL, NULL, '', '', 'Wifi Water Leak Detector : Get notification when there is water leakage, water overflow and water level change to efficiently avoid the accident and damage . Leakage detection Low battery reminder Intelligent Linkage Low power consumption Tool free installation', 'No hub required', '1 year', 'Input Voltage: DC3V LR03 Static current: <10uA Alarm current: <160mA Low-Voltage indication:<2.6V WIFI: 802.1 1b/g/n Installation: Wall mounted Detection: Water sensor Detect Working temperature : -10C to 50 C Working humidity: 95%RH', '◎ WIFI Water leak detector ◎ Real-time detect water ◎ Detecting water leakage ◎ Low battery reminder ◎ low power consumption', NULL, 2500, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(63, 'EKEN Video Doorbell', 'V5', 2, 2, NULL, NULL, NULL, NULL, NULL, 'Product size: 143*75*21mm/5.62*2.95*0.82\'\' Gross weight: 330g Color: White', '', 'WiFi Video Door Bell V5 PIR Motion controll iOS Android app 2 Way intercom SD Card Storage Support', '', '', 'Specification: Brand: EKEN NFC Support: No Opening: F2.35 Touch Screen: No HDMI output: Yes Image Sensors: OmniVision Series Wide angle: 166 degrees Effective megapixels: about 5MP Bluetooth support: Yes Waterproof: Yes. Main Processor (Maximum HD Support): SPCA1628 (720P/30FPS) Screen size: no Screen Storage Card: Memory Card (not included) Sensor size (inch): 1/2.8 inch NightShot functionality: Yes Battery capacity: 18650 batteries excluded Control Support: Yes Supporting Wireless: Yes Additional function: Nightshot Application: Home, Vehicle DVR Support memory card: 32G Lens: f = 2.1mm, F = 2.35 Network: P2P and QR codes Waterproof grade: IP65 Waterproof grade: IP65 Audio: Two-way call, built-in microphone Supported mobile systems: iOS, Android', 'Feature: 1. PIR Motion Detection: EKEN Video Door Bell is equipped with a passive infrared radiation sensor, which can detect the slight movement of the entrance. Receive notifications on your mobile phone when an activity is found near the door. 2. Real-time two-way audio: When someone rings the doorbell, a notification will appear on your mobile phone. You can use this application to open the door remotely and communicate directly with your device. 3. 166-degree wide-angle lens: Use this application to get a complete 166-degree view of your front porch. See your visitors effortlessly. 4. Smart Night Vision: Switch to Night Mode on your app, and the light sensor on the doorbell will provide a clear view at night.', NULL, 2500, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`),
  ADD KEY `products_concept_id_foreign` (`concept_id`),
  ADD KEY `products_cat_id_foreign` (`cat_id`),
  ADD KEY `products_brand_id_foreign` (`brand_id`),
  ADD KEY `products_type_id_foreign` (`type_id`),
  ADD KEY `products_compatibility_id_foreign` (`compatibility_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=64;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `products`
--
ALTER TABLE `products`
  ADD CONSTRAINT `products_brand_id_foreign` FOREIGN KEY (`brand_id`) REFERENCES `brands` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `products_cat_id_foreign` FOREIGN KEY (`cat_id`) REFERENCES `categories` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `products_compatibility_id_foreign` FOREIGN KEY (`compatibility_id`) REFERENCES `compatibilities` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `products_concept_id_foreign` FOREIGN KEY (`concept_id`) REFERENCES `concepts` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `products_type_id_foreign` FOREIGN KEY (`type_id`) REFERENCES `types` (`id`) ON DELETE CASCADE;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
